"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
exports.__esModule = true;
exports.query = void 0;
var graphql_request_1 = require("graphql-request");
exports.query = graphql_request_1.gql(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n\tquery shorts($account: String!) {\n\t\tshorts(first: 100, where: { account: $account }, orderBy: id, orderDirection: $orderDirection: desc) {\n\t\t\tid\n\t\t\tcontractData {\n\t\t\t\tissueFeeRate\n\t\t\t\tcanOpenLoans\n\t\t\t\tminCratio\n\t\t\t\tminCollateral\n\t\t\t\tmaxLoansPerAccount\n\t\t\t\tinteractionDelay\n\t\t\t\tmanager\n\t\t\t}\n\t\t\ttxHash\n\t\t\taccount\n\t\t\tcollateralLocked\n\t\t\tcollateralLockedAmount\n\t\t\tsynthBorrowed\n\t\t\tsynthBorrowedAmount\n\t\t\tisOpen\n\t\t\tcreatedAt\n\t\t\tclosedAt\n\t\t\tliquidations {\n\t\t\t\tid\n\t\t\t\tliquidator\n\t\t\t\tisClosed\n\t\t\t\tliquidatedAmount\n\t\t\t\tliquidatedCollateral\n\t\t\t\ttimestamp\n\t\t\t}\n\t\t\tcollateralChanges {\n\t\t\t\tid\n\t\t\t\tisDeposit\n\t\t\t\tamount\n\t\t\t\tcollateralAfter\n\t\t\t\ttimestamp\n\t\t\t}\n\t\t\tloanChanges {\n\t\t\t\tid\n\t\t\t\tamount\n\t\t\t\tisRepayment\n\t\t\t\tloanAfter\n\t\t\t\ttimestamp\n\t\t\t}\n\t\t}\n\t}\n"], ["\n\tquery shorts($account: String!) {\n\t\tshorts(first: 100, where: { account: $account }, orderBy: id, orderDirection: $orderDirection: desc) {\n\t\t\tid\n\t\t\tcontractData {\n\t\t\t\tissueFeeRate\n\t\t\t\tcanOpenLoans\n\t\t\t\tminCratio\n\t\t\t\tminCollateral\n\t\t\t\tmaxLoansPerAccount\n\t\t\t\tinteractionDelay\n\t\t\t\tmanager\n\t\t\t}\n\t\t\ttxHash\n\t\t\taccount\n\t\t\tcollateralLocked\n\t\t\tcollateralLockedAmount\n\t\t\tsynthBorrowed\n\t\t\tsynthBorrowedAmount\n\t\t\tisOpen\n\t\t\tcreatedAt\n\t\t\tclosedAt\n\t\t\tliquidations {\n\t\t\t\tid\n\t\t\t\tliquidator\n\t\t\t\tisClosed\n\t\t\t\tliquidatedAmount\n\t\t\t\tliquidatedCollateral\n\t\t\t\ttimestamp\n\t\t\t}\n\t\t\tcollateralChanges {\n\t\t\t\tid\n\t\t\t\tisDeposit\n\t\t\t\tamount\n\t\t\t\tcollateralAfter\n\t\t\t\ttimestamp\n\t\t\t}\n\t\t\tloanChanges {\n\t\t\t\tid\n\t\t\t\tamount\n\t\t\t\tisRepayment\n\t\t\t\tloanAfter\n\t\t\t\ttimestamp\n\t\t\t}\n\t\t}\n\t}\n"])));
var templateObject_1;
